### ISSUE TITLE
#outboundproxy - Ensure applications are only allowed through the proxy (or the nat) via network rules

### ISSUE THREAD

**Issue by gdestuynder** [nubisproject/nubis-ha-nat#2]
See also https://github.com/nubisproject/nubis-proxy/issues/2

From IRC:
 kang | 2) where do i find how the usage of the proxy is enforced?  
jd | kang: for 2 you could make a seperate issue in github if you like againstnubis-nat. It will be done in the firewall on there once they exist

**Comment by tinnightcap** [comment]
Once the NATs and Proxies are deployed and the applications configured to use them this can be implemented in the VPC routing tables.

**Comment by tinnightcap** [comment]
This work was completed in the nubis-nat repository. Use of this repository has been deprecated.
